### ISSUE TITLE
Error When Clicking Keppy's MIDI Converter in Open With

### ISSUE THREAD

**Issue by BKB10** [KeppySoftware/Keppys-MIDI-Converter#38]
I right clicked on a MIDI, went into the Open With menu, then clicked Keppy's MIDI Converter.

Here's an image of the error:
[]https://drive.google.com/file/d/1IZZqBV4E4EK58Wv6jLc_1KmipFhrBMvj/view?usp=sharing

The issue is probably caused because you can't open a file like this:
https://drive.google.com/file/d/1l91AyjZj9gANv4XGk9pqRUsYurW79Oi3/view?usp=sharing

**Comment by KaleidonKep99** [comment]
You can actually open files like this, I just forgot to update some parts of the source code.
