### ISSUE TITLE
Using Tal Reverb 4 VST causes crash

### ISSUE THREAD

**Issue by HDSQmid** [KeppySoftware/Keppys-MIDI-Converter#39]
When I attempt to use this VST in the current version of KMC, the app freezes indefinitely (but doesn't crash until I hit the close button) when I begin the render. This is true in both the 32-bit and 64-bit programs
VST download: https://tal-software.com/products/tal-reverb-4
KMC Configuration: (if not included, I haven't changed it from the default)
-  Max Voices: 1000
-  Audio Frequency: 48000Hz
-  Render mode: Real-time simulation
-  VST DSPs: 
-      Loudmax: On
-      Tal Reverb 4 (version 66049)
-      Render to: WAV

What happens: 
Render allocates memory for conversion.
Loudmax settings are set
Application stops responding
CPU usage whilst application is stopped: 0%

This is not an issue with the Tal Reverb 4 VST because this VST works fine with an older version of KMC (Before the rewrite)

**Comment by KaleidonKep99** [comment]
Try replacing the BASS_VST DLLs with the ones from here: https://github.com/r10s/BASS_VST/tree/master/bin

**Comment by HDSQmid** [comment]
Where do I put the DLLs?

**Comment by HDSQmid** [comment]
Didn't work still.

**Comment by KaleidonKep99** [comment]
Fixed in version [18.0.22](https://github.com/KeppySoftware/Keppys-MIDI-Converter/releases/tag/18.0.22).
