### ISSUE TITLE
Crashes on preview

### ISSUE THREAD

**Issue by GloriousYellow** [KeppySoftware/Keppys-MIDI-Converter#40]

**Comment by KaleidonKep99** [comment]
Care to give me more info about this issue?
What version of the converter are you using? Does it happen when using a VST instrument or when using a SoundFont? Are you using any external VST effect?
"Crashes on preview" doesn't really help me debug the issue, since preview works fine for me.

**Comment by GloriousYellow** [comment]
Version is 18.1.0
There are no VST effects

**Comment by GloriousYellow** [comment]
I have narrowed it down. It only crashes if "Ignore notes between two velocity values" is enabled.

**Comment by KaleidonKep99** [comment]
![image](https://user-images.githubusercontent.com/11065274/40386537-461ae008-5e0a-11e8-921d-7999735ce730.png)
Weird, it works for me.
I'll take a look at the issue.

**Comment by KaleidonKep99** [comment]
I can't reproduce the issue.
Try resetting the settings.

**Comment by KaleidonKep99** [comment]
Closed for inactivity.
