### ISSUE TITLE
Install on existing folder unpossible

### ISSUE THREAD

**Issue by bnote** [KeppySoftware/Keppys-MIDI-Converter#41]
Install on existing folder unpossible if it is opened in Far, for example, with error:

> Setup was unable to create the directory "E:\My\Not\Very\Long\Path\Keppy".
> Error 5: Access is denied.

and resul to rollback.
.

**Comment by KaleidonKep99** [comment]
Use the portable version then.
This might be a limit of the NTFS file system.

**Comment by bnote** [comment]
> This might be a limit of the NTFS file system.
Oh, no.  The matter is not in the file system type. Moreover, there is the FAT32 on my target drive. 
It looks as the installer try to completely delete target folder during installation process, and, because this folder is opened in FAR already, it can't delete it.
.

**Comment by KaleidonKep99** [comment]
I still don't know what FAR is. :thinking:

But yeah, KMC always wipes its folder, to make sure that all the outdated files are deleted.

**Comment by bnote** [comment]
> I still don't know what FAR is. 

Later, later ... Everything has its time ...
Maybe you don't listened "Let it be" too? :)

Far is the world known file manager (NC-like), created by Evgeny Roshal, cool сhelyabinsk's man, author of the Rar too. Or you don't know on Rar too?

> KMC always wipes **its** folder ...

_**"Its"**_?! At what moment did my folder, which I created by myself and indicated as the target for the installation only, become _**"Its"**_? 

It is allowed to name installation folder as _**"its"**_, when the folder was created by installator itself, but not, when it was existed already before install ...

> ... to make sure that all the outdated files are deleted.

About which _"outdated files"_ you talk on Install, but not on Repair?
Moreover, you know all of the files, that may be outdated, very well. WTF you kill notthe separate files, but the whole folder, which, moreover, may not belong to you till?

Please, do the following:

1. Create the destination folder
2. Change date attributes of folder to day ago
3. Close your  file manager
4. Install KMC
5. Check date attributes of folder

Be sure that all of them was changed to current day.

It means, that the folder was deleted completely in installation process. I.e. - by you, dear Sir. 

To be more and fully sure, do the same, but in addition:
...
2.1 Create any file inside it
...
5.1 Be sure, that you kill this file too ...

You are very freely on computers that are not yours.
.

**Comment by KaleidonKep99** [comment]
I never had a chance to use FAR, there's no need to be arrogant about it.
I don't need the "world known file manager" installed on my PC, I'm fine with Windows Explorer.

If you want to install KMC outside of the Program Files folder... Just use the portable version then? 
It would save you time from creating useless issues like this, and attacking people who are just trying to help you.

Do you want to help me solve the issues? Stop being a cheeky asshole towards me, and I will.

**Comment by longnguyen2004** [comment]
You wasted this much time trying to ask a dumb question when you can just download the portable version and move on.
