### ISSUE TITLE
sf2pack extension not accepted

### ISSUE THREAD

**Issue by bnote** [KeppySoftware/Keppys-MIDI-Converter#43]
I was forced to look for soundfonts and take them form another app.
However this file chorium.sf2pack was not recognised with error:
> Error
> This is not a valid soundfont!
> Select a soundfont and try again.

It was just enough to change extension for it to "sf2".

So, **not soundfont is invalid, but file extension** only. 
It is a two big differences, as they say in Odessa :)

Yeah, there is a list of supported extensions, but it closing up by the new opened file selection dialog window, and extensions are not present in it, but the non-informative "Soundfont files" description only.
.

**Comment by KaleidonKep99** [comment]
I'll fix it in the next release.
