### ISSUE TITLE
midi files could not be processed

### ISSUE THREAD

**Issue by ewewo2** [KeppySoftware/Keppys-MIDI-Converter#44]
i have a bunch of midi files which cannot be processed. is there a way to fix it? example file is attached.
[midi.zip](https://github.com/KeppySoftware/Keppys-MIDI-Converter/files/2088163/midi.zip)

**Comment by KaleidonKep99** [comment]
These MIDI files are empty, they don't contain anything.

**Comment by ewewo2** [comment]
sorry uploaded the wrong files. here's the correct one:
[bassdrum_00009.zip](https://github.com/KeppySoftware/Keppys-MIDI-Converter/files/2088200/bassdrum_00009.zip)

**Comment by KaleidonKep99** [comment]
That's still empty.

**Comment by ewewo2** [comment]
some midi editors/sequencers will not be able to read the content but for example cubase, toon,track ezplayer pro, GNMIDI for Windows, GNMIDI Comman Line Utilities and even some IOS and Android Apps can read the MIDI content off this file. I have a bunch of them and some Midi Packs are in the same sub format. It would be so great if KMC could read this kind of files

**Comment by KaleidonKep99** [comment]
This is beyond what I can do, Keppy's MIDI Converter is just a *GUI* on top of the BASS librariers.
Send the MIDI to Ian Luck, so he can analyze and maybe do something about it.
http://www.un4seen.com/forum/?board=1
