### ISSUE TITLE
feature request: command prompt (windows)

### ISSUE THREAD

**Issue by ewewo2** [KeppySoftware/Keppys-MIDI-Converter#47]
can kmc be fully controlled via command prompt line (windows)?

ps: wow, you're very fast, adding new features and fixing issues!

**Comment by luminastudio** [comment]
This is what I need :)

**Comment by KaleidonKep99** [comment]
I'll see what I can do about it.
It'll obviously be limited, when compared to the GUI. ;)

**Comment by KaleidonKep99** [comment]
*On hold.*
