### ISSUE TITLE
feature request: saving effect chain presets

### ISSUE THREAD

**Issue by ewewo2** [KeppySoftware/Keppys-MIDI-Converter#48]
it would be great if we could manually save the vst effect chains and individual to load them after program restart.

**Comment by KaleidonKep99** [comment]
Eh... Alright. I'll try.

**Comment by ewewo2** [comment]
cool. it would be great if it would work something like this: select MIDI File, select soundfont, select presaved effect chain

**Comment by KaleidonKep99** [comment]
*On hold.*
