### ISSUE TITLE
x64 version complains about large MIDIs in Real Time Conversion

### ISSUE THREAD

**Issue by minelolpride** [KeppySoftware/Keppys-MIDI-Converter#50]
v18.1.3

I have been able to render large MIDIs through RT conversion mode before, but it seems to not let me now. If I try, this happens...
![capture](https://user-images.githubusercontent.com/16008698/41309379-e5450e24-6e3b-11e8-8e8d-be15e0589b8e.PNG)

If I set the render mode to Standard, it works fine. This leads me to believe this is intentional? (At least that's what I think...)

**Comment by KaleidonKep99** [comment]
I can't test the issue without the original MIDI.

**Comment by minelolpride** [comment]
Sending via Discord

**Comment by KaleidonKep99** [comment]
The MIDI has been merged using an hex editor.

Invalid issue. Closed.
