### ISSUE TITLE
"Limit" is spelled wrong

### ISSUE THREAD

**Issue by DevanWolf** [KeppySoftware/Keppys-MIDI-Converter#53]
It's spelled "Liimt" instead. Located in Advanced Settings dialog. See pull request #52 for file difference.

**Comment by KaleidonKep99** [comment]
I forgot to say fixed.
Well, fixed!

**Comment by DevanWolf** [comment]
I still see the typo in the latest version so it is still not fixed.

**Comment by DevanWolf** [comment]
Please fix that now in 18.2.8!
