### ISSUE TITLE
feature request: Render to flac or alac. As well as some more midi options.

### ISSUE THREAD

**Issue by Nukley** [KeppySoftware/Keppys-MIDI-Converter#54]
I would like to render to flac ot alac so I can get the best audio quality. I also had this app for a while, https://play.google.com/store/apps/details?id=net.volcanomobile.midiplayer&hl=en_US It has a TON of midi options and I made it sound really good. The only problem is, even if I hook up my phone to my computer, it doesn't sound as good as it does on my phone...

**Comment by Nukley** [comment]
![screenshot_2018-09-08-17-04-11](https://user-images.githubusercontent.com/26724236/45258674-95ce0b00-b389-11e8-8942-15bfc366af9c.png)
![screenshot_2018-09-08-17-03-55](https://user-images.githubusercontent.com/26724236/45258676-98c8fb80-b389-11e8-839e-f8a4389e47bc.png)
![screenshot_2018-09-08-17-04-01](https://user-images.githubusercontent.com/26724236/45258677-9a92bf00-b389-11e8-8c73-fecb90547191.png)

**Comment by KaleidonKep99** [comment]
KMC uses BASSMIDI, so these additional ADLMIDI settings can not be added. Sorry.

I tried adding support for FLAC, but BASSenc doesn't seem to like it. It ends the file output abruptly, leaving a huge FLAC file behind, which is unplayable too.

I'll see what I can do about it, though.

**Comment by KaleidonKep99** [comment]
FLAC still won't work properly with BASSenc. I can't do much about it.
Closed.
